### ISSUE TITLE
Requirement - low bandwidth

### ISSUE THREAD

**Issue by drewdrew122** [racerecords/RaceRecords#18]
The interface should be designed to work with a low bandwidth connection.  We have connectivity to the internet from the laptop, but it's not the highest quality.  

If its possible to make the system able to be downloaded to our local machine to run local, then save the data to the cloud that would be helpful

**Comment by mcmillanator** [comment]
# TODO
- [ ] Add local storage to the UI
- [ ] Async with the server after updating the table
- [ ] Handle sync failures gracefully and re-attempt sync periodically until success

**Comment by mcmillanator** [comment]
http://test-race.stanleymcmillan.com/reports/1 has been updated with the prototype UI and "offline mode" added.  You'll have to put the browser into offline mode to test it.  Nothing in the readings table is being saved to the database yet, so opening the page in an anonymous browser will give you a blank table.  In the regular browser you will be able to close the page and re-open without loosing data.  You should be able to go as far as rebooting the computer and still have your data when you come back.  You can even clear the cache and keep your data.  If you delete all application data then it's gone.  The table is stored in the Index DB.  Everything has been developed for Chrome.  Will test in FireFox at some point, and probably Safari.  No plans for supporting IE/Edge.

TODO:
- [ ] Test Firefox
- [ ] Test Safari

**Comment by mcmillanator** [comment]
I'm going to close this as completed.  I think what i have is good enough for MVP.  I'll have to go back and to a major refactor at some point.

**Comment by mcmillanator** [comment]
Forgot to iterate over the entire table when syncing to the server.
